### PR TITLE
Building Executables

### PR DESCRIPTION
**Pull request by YisusGaming**
implementation of #1.
Right now, it has some flaws. For example, right now the only way to use `ishere` is to compile it. I'll be fixing this.

I also bumped the version to `2.0.0`. I thought a major update should work since it's changing how the script behaves.
I created a section in the Readme called "Building an executable" which I'll be filling with step-by-step documentation.

In short, the implementation is not quite ready but I'm making this PR to show the progress.

if any changes are needed, please tell me and I'll make those changes.

### CODE REVIEW

**Review by shawnjb — APPROVED** [review]
I've reviewed the changes in your pull request and made some adjustments to the Makefile to enhance its usability. Here's a summary of the changes:

1. **VCPKG_ROOT Environment Variable Check:**
   I've added a check to the Makefile to ensure that the `VCPKG_ROOT` environment variable is defined. If it's not defined, the Makefile will display an error message instructing the user to set it. This is to ensure that users are aware of the requirement and provide clear guidance on how to proceed.

2. **Usage of VCPKG_ROOT:**
   The Makefile now uses the `VCPKG_ROOT` environment variable to determine the path to your Vcpkg installation directory. This should help users provide the correct path to their Vcpkg installation without directly modifying the Makefile.

```makefile
BUILD_DIRS=build build/src
$(shell mkdir -p $(BUILD_DIRS))

ifndef VCPKG_ROOT
$(error VCPKG_ROOT is not defined. Please set it to the Vcpkg installation directory.)
endif

LUA_INCLUDE := -I$(VCPKG_ROOT)/installed/x64-windows/include
LUA_VM := -L$(VCPKG_ROOT)/installed/x64-windows/lib -llua

# Rest of the Makefile
```

**Comment by YisusGaming** [comment]
It seems good. But wouldn't this fail if the user has a different folder structure? For example, in my case, Lua's includes are in "/root/include".

**Comment by YisusGaming** [comment]
And also, the documentation for building executables in the readme is missing!

**Comment by YisusGaming** [comment]
Although, I do have a question. Wouldn't this fail if the user is trying to build this in a windows x86 (32 bits) system?

**Comment by YisusGaming** [comment]
It seems a bit more complicated than the previous implementation, since the users only had to use this command to build:
```
make LUA_INCLUDE=path LUA_VM=path
```
But I think is fine.

Something you should consider (if you haven't already) is to instruct the users to set `build/` in their system's path.
That way, users can now run the program as any other command:
```
ishere [directory] <filename>
```

**Comment by shawnjb** [comment]
> It seems a bit more complicated than the previous implementation, since the users only had to use this command to build:
> 
> ```
> make LUA_INCLUDE=path LUA_VM=path
> ```
> 
> But I think is fine.
> 
> Something you should consider (if you haven't already) is to instruct the users to set `build/` in their system's path. That way, users can now run the program as any other command:
> 
> ```
> ishere [directory] <filename>
> ```

I agree, I will add that shortly.

**Pull request merged**
